### ISSUE TITLE
[Suggestion] Create Sub-folder option.

### ISSUE THREAD

**Issue by th109663** [d8ahazard/deluge-extractorplus-plugin#1]
It would be really useful to be able to toggle the option to create a subfolder for all extracted files when using any of the 3 extraction placement options.

My main use case for this is when working with torrents of exactly 1 zip file. I like the ability to have all my zips in one location and their extracted contents in subfolders. without being mixed together.

This already exists in the basic "Extractor" plugin.

**Comment by d8ahazard** [comment]
> It would be really useful to be able to toggle the option to create a subfolder for all extracted files when using any of the 3 extraction placement options.
> 
> My main use case for this is when working with torrents of exactly 1 zip file. I like the ability to have all my zips in one location and their extracted contents in subfolders. without being mixed together.
> 
> This already exists in the basic "Extractor" plugin.

Sounds simple enough.

Just for clarity's sake, can you provide one (or several) examples of what the desired behavior would be?

Like, I'm picturing a checkbox that would enable the feature "Create subfolder when extracting" (or something), but then what determines the subfolder name, etc. ?

**Comment by th109663** [comment]
Yeah that sounds good on the UI side
I'd expect it to extract into a folder of the same name as the zip

## 1 File
E.G. A torrent of 1 file named Data.Zip
InPlace + Torrent root (same behaviour)
-  path/to/torrent/
   - Data.zip
   - Data/
     - *Data contents*

In Folder
- FOLDER/
  - Data/
    - *Data contents*

## Many files

Another example with more than one file
E.G. A torrent of 3 files layed out as such
- TORRENTNAME/
  - Data.zip
  - Manual/
    - English.zip
    - French.zip

Would result in this

In Place:
- TORRENTNAME/
  - Data.zip
  - Data/
    - *Data.zip content*
  -  Manual/
      - English.zip
      - English/
        - *English.zip content*
      - French.zip
      - French/
        - *French.zip content*

Torrent Root:

- TORRENTNAME/
  - Data.zip
  - Data/
    - *Data.zip content*
  - English/
    - *English.zip content*
  - French/
    - *French.zip content*
  -  Manual/
      - English.zip
      - French.zip
                    
Note: I'm unsure how the In Folder currently works, but I'd imagine it doing something like this for the above example.

- FOLDER/
  - TORRENTNAME/
    - Data/
      - *Data.zip content*
    - Manual/
      - English/
        - *English.zip content*
      - French/
        - *French.zip content*


Sorry if that's a little hard to read, I got a little carried away 😅

**Comment by d8ahazard** [comment]
Gotcha. So, we're just creating a directory with the *archive* name.

If I'm being optimistic, I should have this pushed this afternoon, possibly tomorrow. Thanks for the suggestion. :D

**Comment by d8ahazard** [comment]
Implemented with release https://github.com/d8ahazard/deluge-extractorplus-plugin/commit/b9f7e8dbd16b634e5a0150d8e944dd42dd66b075
